### ISSUE TITLE
Table doesn't resize to fit window size

### ISSUE THREAD

**Issue by aaronomnis1** [feentech/leroy#1]
Table doesn't resize to fit window size

**Comment by kiernfeeney** [comment]
Do you mean the fields or the table itself? Does it not shrink to size or not grow? Please elaborate.

**Comment by aaronomnis1** [comment]
it does not shrink / grow to match the window size. If I expand the size of my window to max screen it looks fine but if I shrink it to a smaller sized window the table does not shrink with the browser window

**Comment by kiernfeeney** [comment]
I think the best thing to do would be make the X-axis scrollable so instead
of the content overflowing you get a scrollable table.

**Comment by kiernfeeney** [comment]
The X-axis on the user page scrolls so the data within the table never gets malformed.
