### ISSUE TITLE
Profanity allowed - need some sort of filter / blacklist of words

### ISSUE THREAD

**Issue by aaronomnis1** [feentech/leroy#11]
Profanity allowed - need some sort of filter / blacklist of words

Currently allowed in both Username and Email

**Comment by kiernfeeney** [comment]
We can discuss this further but I don't think it's needed. There is no open registration so I'm not worried about spam accounts and this would just add unnecessary complications. Accounts can be deleted by any admin so if a profane account name pops up it can either be renamed or deleted. Also, for maximum compatibility profane email addresses should be allowed. Although I'm not against adding a domain blacklist.
