### ISSUE TITLE
Update README.md on how to setup local dev environment

### ISSUE THREAD

**Issue by kiernfeeney** [feentech/leroy#18]
Include dependencies and basic commands on how to get setup.

**Comment by kiernfeeney** [comment]
I created a basic quick start guide in the readme but I would like @aaronomnis1 or @trl6895 to try it out and recommended any modifications.

**Comment by trl6895** [comment]
- link to postgres download leads to a 404

- issues with "php artisan migrate" command, leads to following error:
       PDOException::("could not find drvier")

       *FIX* go to C:\xampp\php and open php.ini. Between lines 922-947 uncomment the following:

              extension=gd
              extension=intl
              extension=mbstring
              extension=exif
              extension=pdo_pgsql
              extension=pgsql

**Comment by kiernfeeney** [comment]
> * link to postgres download leads to a 404
> * issues with "php artisan migrate" command, leads to following error:
>   PDOException::("could not find drvier")
>   ```
>    *FIX* go to where php is downloaded and open php.ini. Between lines 922-947 uncomment the following:
>   
>           extension=gd
>           extension=intl
>           extension=mbstring
>           extension=exif
>           extension=pdo_pgsql
>           extension=pgsql  
>   ```

The fix is to actually just uncomment
```
        extension=pdo_pgsql
        extension=pgsql  
```

The other extensions are un-related but should be uncommented regardless.

**Comment by kiernfeeney** [comment]
I believe this has been adequately documented so I'm going to close this issue.
