### ISSUE TITLE
Spam Titan API Integration layout

### ISSUE THREAD

**Issue by aaronomnis1** [feentech/leroy#39]
->   = section
1,2,3,4,5    = subsection
i,ii,iii,iv,v = optionally filter section data by subsection

Spam Titan
  -> General Dashboard
      1. Show Licensing Stats (https://api-spamtitan.titanhq.com/#api-reports-licenseusage)
          i. Display description / license_number / type / number_of_users / issued_date / expiry_date and use issued expiry to determine average and max usage (https://api-spamtitan.titanhq.com/#api-license-checkLicenseKey)
      2. Show Scan Summary stats (https://api-spamtitan.titanhq.com/#api-reports-scansummary)
      3. Show Client Certificate info (https://api-spamtitan.titanhq.com/#api-tls-getClientCert)
      4. Check if support port is open and if it is list the current open port (https://api-spamtitan.titanhq.com/#api-supportport-GetSupportPort)
  -> Show Mail Queue for all, active and deferred, or just deferred (https://api-spamtitan.titanhq.com/#api-mailqueue)
  -> Quarantine report
  -> Whitelist / Blacklist
      1. Whitelist for all clients (https://api-spamtitan.titanhq.com/#api-allowlist-GetAllowList)
      2. Blacklist for all clients (https://api-spamtitan.titanhq.com/#api-blocklist-GetBlocklist)
  -> Message Trace
      1. Filtering options to search for specific mail (https://api-spamtitan.titanhq.com/#api-history-list)
  -> List Domains
      1. Check MX Record to validate records are in place (email.omnis1.com and email2.omnis1.com - priority optional)
      2. Show email authentication details
          i. SPF - list spf record
	  ii. DMARC - list dmarc record
	  iii. DKIM - list selector (https://api-spamtitan.titanhq.com/#api-domains-DkimList) and verify DKIM (https://api-spamtitan.titanhq.com/#api-domains-DkimVerify)
	  iv. Convert domains to IP and test for RBL - if listed, flag (https://api-spamtitan.titanhq.com/#api-rbl-testRbl)
	  v. List / Create Whitelist per client
	  vi. List / Create Blacklist per client
	  vii. Break down Mail queue per client
	  viii. Break down Quarantine per client

**Comment by kiernfeeney** [comment]
I don't think there will be an actual spamtitan section but instead more of a general email section that has a spamtitan plugin. I'll talk to @aaronomnis1 about this next week but I'm closing this issue.
