### ISSUE TITLE
Limit News Feed results

### ISSUE THREAD

**Issue by aaronomnis1** [feentech/leroy#46]
Please limit news feed results and provide navigation via page numbers

e.g. searching for 'IT' results in over 3000 pages and it shows the page numbers below the news articles. Ideally it would show a handful of them (9? 12?) and then have a number of pages below to navigate the rest of the results (page 1 to 250 or whatever and have a next / previous button)

This may not be necessary until changing the home dashboard around

**Comment by kiernfeeney** [comment]
News has been removed. Will come back in the home page but only a few results will be displayed. Closing this.
