### ISSUE TITLE
Deleting user shows toast of UUID instead of Username

### ISSUE THREAD

**Issue by aaronomnis1** [feentech/leroy#5]
Deleting user shows toast of UUID instead of Username

Assuming this is not intentional as it shows the Username when you create the user but shows the UUID when you delete it

**Comment by kiernfeeney** [comment]
Currently, this is expected as to delete a user you make a `DELETE` request to `/api/users/<uuid>`. I may change the API to return the object of the deleted user on success so I don't have to pass additional arguments to the JavaScript `class Users { delete(uuid) }` function, which is only expecting one argument.

**Comment by kiernfeeney** [comment]
Since this is what is expected, I'm going to close this issue. May revisit later.
