### ISSUE TITLE
Modify notification banner on TLS Certs

### ISSUE THREAD

**Issue by aaronomnis1** [feentech/leroy#54]
Modify notification banner on TLS Certs expiry date to increase legibility (TLS Certs -> whatever cert you pick -> UUID). Additionally, adding a 1px black border / stroke around text would increase legibility a lot too.

Suggested:
less than 30 days        - red banner with white text
30 days to 60 days     - orange banner with white text
greater than 60 days  - green banner with white text

**Comment by kiernfeeney** [comment]
I agree on everything but the text stroke... I may remove the bold font and see if that helps.

**Comment by kiernfeeney** [comment]
< 1209600 seconds (14 days) = error
< 2592000 seconds (30 days) && > 1209600 = warning
> 2592000 seconds = success
