### ISSUE TITLE
Table does not sort by default or allow for sorting on demand

### ISSUE THREAD

**Issue by aaronomnis1** [feentech/leroy#9]
Table does not sort by default or allow for sorting on demand

Does not sort by default (Username?) or allow you to sort by your preferred data type on demand

**Comment by kiernfeeney** [comment]
[This commit](https://github.com/feentech/leroy/commit/95a8d2c8dd9029fa663f0368982f5c6c0eb4979c) I finalized the table sorting function and am happy with the behavior. I applied it to the users table but like the table search/hide function this can be applied anywhere.
